"""create positions and agent_cycles tables

Revision ID: e079da9eee24
Revises: 
Create Date: 2026-08-26 13:30:10.202011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e079da9eee24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_time', sa.DateTime(), nullable=False),
    sa.Column('timeframe_scope', sa.String(length=10), nullable=False),
    sa.Column('symbols_scanned', sa.Integer(), nullable=True),
    sa.Column('signals_detected', sa.Integer(), nullable=True),
    sa.Column('groq_approved', sa.Integer(), nullable=True),
    sa.Column('risk_approved', sa.Integer(), nullable=True),
    sa.Column('orders_placed', sa.Integer(), nullable=True),
    sa.Column('portfolio_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('allocated_capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('realized_pnl_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('groq_confidence', sa.Integer(), nullable=True),
    sa.Column('groq_reasoning', sa.Text(), nullable=True),
    sa.Column('groq_go', sa.Boolean(), nullable=True),
    sa.Column('risk_approved', sa.Boolean(), nullable=True),
    sa.Column('risk_block_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_strategy_id'), 'positions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_strategy_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('agent_cycles')
    # ### end Alembic commands ###
